vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        project_images:
            uri_prefix: /uploads/projects
            upload_destination: '%kernel.project_dir%/public/uploads/projects'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
